# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(default=1, max_length=20, verbose_name='验证码'),
            preserve_default=False,
        ),
    ]
