# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_emailverifyrecord_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='alias',
            field=models.CharField(default=1, max_length=50, verbose_name='别名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default=1, max_length=30, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
