# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20181109_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headp',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/head', verbose_name='头像'),
        ),
    ]
