# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_auto_20181109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', '男'), ('0', '女')], default='1', max_length=10, null=True, verbose_name='性别'),
        ),
    ]
