# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0008_auto_20181109_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headp',
            field=models.ImageField(blank=True, default='', null=True, upload_to='headphoto', verbose_name='头像'),
        ),
    ]
