# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0009_auto_20181112_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headp',
            field=models.ImageField(blank=True, default='touxiang.png', upload_to='headphoto', verbose_name='头像'),
        ),
    ]
