# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0012_auto_20181122_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='000000', max_length=30, verbose_name='邮编'),
        ),
    ]
