# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('des', models.CharField(max_length=1000, verbose_name='详细描述')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
